### ISSUE TITLE
Some incorrect data

### ISSUE THREAD

**Issue by RainSalamander** [te1/monsterbuddy-mhst2#174]
- Barioth listed as a technical monstie, is actually speed.
- 5-star Palamute den shows 8-star expedition's contents, observed contents of nests (list likely partial, R ticket): normal palamute only, mizutsune, p.ludroth, g.nargacuga, legiana, khezu, gravios.

<sub>Platform:firefox

**Comment by te1** [comment]
Thanks for the feedback! New version is out to address that.

A note on the co-op dens: You can find more common eggs (e.g. Khezu, Gravios) when using R or N tickets. You won't find them when using SR tickets so I don't put them on the list.
